syntax = "proto3";

import "app/morphe/extension/youtube/innertube/guide_response.proto";

package app.morphe.extension.youtube.innertube;

option optimize_for = LITE_RUNTIME;
option java_package = "app.morphe.extension.youtube.innertube";
option java_outer_classname = "BrowseResponseOuterClass";

// Tab of singleColumnBrowseResultsRenderer.
message BrowseTab {
    TabRenderer tabRenderer = 58174010;
}

message TabRenderer {
    NavigationEndpoint endpoint = 1;
    bool selected = 3;
    string tabIdentifier = 11;
}
