name: Sync Morphe patches

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * *"

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout my repository
        uses: actions/checkout@v4

      - name: Clone Morphe patches
        run: |
          git clone --depth=1 https://github.com/MorpheApp/morphe-patches.git temp-morphe

      - name: Copy Morphe files to root
        run: |
          rsync -av \
            --exclude='.git' \
            --exclude='.github' \
            temp-morphe/ ./

          rm -rf temp-morphe

      - name: Commit and push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add .

          if git diff --cached --quiet; then
            echo "No changes"
          else
            git commit -m "Sync Morphe patches"
            git push
          fi
